### ISSUE TITLE
获取媒体信息失败

### ISSUE THREAD

**Issue by cjzmn** [Makememo/MemoAI#5]
在转Youtube视频时候，会显示“获取媒体信息”，这个时间很久，而且之后总是会显示“获取媒体信息失败”，想问下是怎么回事？是要把Youtube的视频下载之后转换吗？

**Comment by Makememo** [comment]
代理问题，需要前往设置 - 代理设置 - 开启系统代理。

**Comment by cjzmn** [comment]
OK，已经解决

**Comment by cjzmn** [comment]
对了，为什么输入Youtube链接以后，还是下载视频失败呀？我是在科学上网的情况下弄的。

**Comment by Makememo** [comment]
能否描述一下使用步骤和具体链接，方便我们复现。

**Comment by Shawn0720** [comment]
我在海外，也看到同样信息
```
[info 21:37:48.026 (error)]  ----------------------------- application starting [2023-08-27-09-37-48] ---------------------------------------
[info 21:37:48.176        ]  自动获取系统代理
[info 21:37:48.337        ]  表示没有配置代理
[error 21:37:48.573        ]  Error occurred in handler for 'set-title-bar-overlay': TypeError: undefined is not a function
    at evalmachine.<anonymous>:1:651821
    at node:electron/js2c/browser_init:2:97846
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81359)
    at EventEmitter.emit (node:events:513:28)
[info 21:37:48.581        ]  Checking for update
[info 21:37:48.601        ]  检测激活状态
[info 21:37:49.247        ]  Setting changed msg
[error 21:37:49.249        ]  Error occurred in handler for 'set-title-bar-overlay': TypeError: undefined is not a function
    at evalmachine.<anonymous>:1:651821
    at node:electron/js2c/browser_init:2:97846
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81359)
    at EventEmitter.emit (node:events:513:28)
[info 21:37:49.666        ]  Update for version 1.0.5 is not available (latest version: 1.0.5, downgrade is allowed).
[info 21:38:29.336        ]  [
  'https://www.youtube.com/watch?v=JTfhYyTuT44',
  '-f',
  'best',
  '--dump-json'
]
[error 21:38:29.341        ]  Error occurred in handler for 'ytdlp-get-info': Error: 
Error code: Error: spawn /Applications/Memo.app/Contents/Resources/app.asar.unpacked/node_modules/ytdlp-static/bin/darwin/yt-dlp ENOENT
    at YTDlpWrap.createError (/Applications/Memo.app/Contents/Resources/app.asar/node_modules/ytdlp-static/dist/index.js:161:16)
    at /Applications/Memo.app/Contents/Resources/app.asar/node_modules/ytdlp-static/dist/index.js:57:38
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
代理设置里面选择 禁用代理 或者 使用系统代理设置 都无效

**Comment by Shawn0720** [comment]
我的问题解决了，关闭高级下载就可以了。
